#pragma once

#include "asset/AssetFwd.hpp"
#include "asset/ShaderProgramAsset.hpp"

#include <cstddef>
#include <cstdint>
#include <limits>
#include <string>
#include <vector>

namespace rubia::asset
{

inline constexpr uint32_t kInvalidShaderBinding =
    std::numeric_limits<uint32_t>::max();

struct MaterialDescriptorBinding
{
    uint32_t set = 1;
    uint32_t binding = kInvalidShaderBinding;
};

struct MaterialParameterBlockDesc
{
    MaterialDescriptorBinding descriptor{1, 0};
};

enum class MaterialValueType
{
    Float,
    Float2,
    Float3,
    Float4,
    Matrix4,
    Int,
    UInt,
    Bool
};

struct MaterialParameterDesc
{
    std::string name;
    MaterialValueType type = MaterialValueType::Float;
    uint32_t byteOffset = 0;
    bool required = false;
};

struct MaterialTextureSlotDesc
{
    std::string name;
    uint32_t slot = 0;
    bool required = false;
    MaterialDescriptorBinding imageBinding;
    MaterialDescriptorBinding samplerBinding;
};

struct MaterialParameterMetadata
{
    std::string name;
    bool required = true;
};

/// Semantic slot and image/sampler pairing. Binding numbers are reflected.
struct MaterialTextureSlotMetadata
{
    std::string name;
    std::string imageResource;
    std::string samplerResource;
    bool required = true;
};

/// Defines the parameter and texture interface accepted by one material kind.
class MaterialTemplateAsset final
{
public:
    struct CreateInfo
    {
        std::string name;
        ShaderProgramAssetHandle program;
        uint32_t materialSet = 1;
        // All reflected parameters are required unless overridden here.
        std::vector<MaterialParameterMetadata> parameters;
        std::vector<MaterialTextureSlotMetadata> textureSlots;
    };

    /// Generated by MaterialTemplateBuilder; callers author CreateInfo only.
    struct CompiledCreateInfo
    {
        std::string name;
        ShaderProgramAssetHandle program;
        MaterialParameterBlockDesc parameterBlock;
        uint32_t parameterDataSize = 0;
        std::vector<MaterialParameterDesc> parameters;
        std::vector<MaterialTextureSlotDesc> textureSlots;
        std::vector<ProgramResourceBinding> bindings;
        uint64_t programInterfaceSignature = 0;
        uint64_t schemaSignature = 0;
    };

    MaterialTemplateAsset() = default;
    explicit MaterialTemplateAsset(CompiledCreateInfo createInfo);

    void create(CompiledCreateInfo createInfo);
    void reset() noexcept;

    [[nodiscard]] const std::string& name() const noexcept { return name_; }
    [[nodiscard]] ShaderProgramAssetHandle program() const noexcept { return program_; }
    [[nodiscard]] const MaterialParameterBlockDesc& parameterBlock() const noexcept
    {
        return parameterBlock_;
    }
    [[nodiscard]] uint32_t parameterDataSize() const noexcept { return parameterDataSize_; }
    [[nodiscard]] const std::vector<MaterialParameterDesc>& parameters() const noexcept { return parameters_; }
    [[nodiscard]] const std::vector<MaterialTextureSlotDesc>& textureSlots() const noexcept { return textureSlots_; }
    [[nodiscard]] const std::vector<ProgramResourceBinding>& bindings() const noexcept { return bindings_; }
    [[nodiscard]] uint64_t schemaSignature() const noexcept { return schemaSignature_; }
    [[nodiscard]] uint64_t programInterfaceSignature() const noexcept
    {
        return programInterfaceSignature_;
    }

    [[nodiscard]] static uint32_t valueSize(MaterialValueType type) noexcept;

private:
    std::string name_;
    ShaderProgramAssetHandle program_;
    MaterialParameterBlockDesc parameterBlock_;
    uint32_t parameterDataSize_ = 0;
    std::vector<MaterialParameterDesc> parameters_;
    std::vector<MaterialTextureSlotDesc> textureSlots_;
    std::vector<ProgramResourceBinding> bindings_;
    uint64_t programInterfaceSignature_ = 0;
    uint64_t schemaSignature_ = 0;
};

} // namespace rubia::asset
